server:
  port: 9004
  servlet:
    context-path: /

spring:
  application:
    name: medical_mobile
  devtools:

    restart:
      enabled: true
      additional-paths: src/main/java


dubbo:
  scan:
    base-packages: com.ujiuye.controller
  registry:
    address: zookeeper://10.10.33.120:2181
    timeout: 100000

fileUploadPath: D:/fileupload/img/