server:
  port: 9003
  servlet:
    context-path: /

spring:
  application:
    name: medical_controller
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  freemarker:
    cache: false
  redis:
    host: 10.10.33.120
    port: 6379
    password: 123456

dubbo:
  scan:
    base-packages: com.ujiuye.controller, com.ujiuye.service
  registry:
    address: zookeeper://10.10.33.120:2181
    timeout: 100000

fileUploadPath: D:/fileupload/img/
ordersettingUploadPath: D:/fileupload/ordersetting